### ISSUE TITLE
mimq-client enhancements

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/go-mimq-client#7]
Please:
Refactor the code so the tool can be used to test each component of srv1, srv2 or process individually without dependency on building the rest of the solution.

**Comment by mahnouman** [comment]
@haitham911 please check if we still need the mimq test tool or the RabbitMQ tool that you would will do the trick for integration testing?

**Comment by GINAGC** [comment]
@haitham911 can you confirm the status of this task?

**Comment by mahnouman** [comment]
Closing this as the solution implemented in other way
